ON-16719: move deb detemplating up into mkdist alongside rpm

diff --git a/scripts/lib/mkdist/preprocess_source b/scripts/lib/mkdist/preprocess_source
--- a/scripts/lib/mkdist/preprocess_source
+++ b/scripts/lib/mkdist/preprocess_source
@@ -1,5 +1,5 @@
 # SPDX-License-Identifier: BSD-2-Clause
-# X-SPDX-Copyright-Text: (c) Copyright 2017-2024 Advanced Micro Devices, Inc.
+# X-SPDX-Copyright-Text: (c) Copyright 2017-2026 Advanced Micro Devices, Inc.
 
 # This file is included by scripts that need to prepare Onload source files
 # for distribution to customers.
@@ -8,6 +8,14 @@ year=$(date '+%Y')
 # Copyright banner for version.h
 banner="Copyright (c) 2002-$year Advanced Micro Devices, Inc."
 git=${GIT_PATH:-"git"}
+
+validate_name_ver() {
+  echo "$2" | LC_ALL=C grep -Eq '^[[:alnum:]_.~+-]+$' || fail "$1 string did not validate: $2"
+}
+
+validate_title() {
+  echo "$2" | grep -Eq '^[[:alnum:]_.~+ -]+$' || fail "$1 string did not validate: $2"
+}
 
 copy_distfiles() {
   # Grab top-level files.
@@ -72,14 +80,38 @@ update_product_strings() {
   mv scripts/onload_misc/dkms.conf dkms.conf
 }
 
+instantiate_debian_template() {
+  local product="$1"
+  local version="$2"
+  local soversion=$(awk '/^ONLOAD_EXT_VERSION_MAJOR/{print $3}' mk/site/libs.mk)
+
+  validate_name_ver soversion "$soversion"
+
+  try mv scripts/debian/debian-templ debian
+  try find debian -type f ! -path 'debian/source/*' -exec \
+    sed -i -e "s/#VERSION#/$version/g" \
+           -e "s/#TYPE#/$product/g" \
+           -e "s/#SOVERSION#/${soversion}/g" '{}' +
+
+  for f in debian/type-*; do
+    try mv "$f" "debian/$product-${f#debian/type-}"
+  done
+}
+
 # This is a wrapper around the various preprocessing stages for environments
 # with appropriately-defined global variables.
 preprocess_source() {
   [ -n "$src_rev" ] || src_rev=$(cd "$TOP" && "$git" rev-parse --short=7 HEAD)
 
+  validate_name_ver product "$product"
+  validate_name_ver version "$version"
+  validate_name_ver src_rev "$src_rev"
+  validate_title Product "$Product"
+
   copy_distfiles "$distfiles_d"
   update_readme_strings "$product" "$version" "$src_rev"
   update_product_strings "$Product" "$product" "$version"
+  instantiate_debian_template "$product" "$version"
 }
 
 
