ON-16040: Move adduser from onload_install to onload_tool
Previously, RPM/DEB installed onload_install just to run one command.
As this one command depended on onload_tool's configuration file,
the function has been moved.

Also adds -v verbose options to onload_tool.

diff --git a/scripts/onload_tool b/scripts/onload_tool
--- a/scripts/onload_tool
+++ b/scripts/onload_tool
@@ -20,6 +20,7 @@ usage() {
   err "  $me mknod <driver-name>          - make /dev/<driver-name>"
   err "  $me mod_params <driver-name>     - return module parameters"
   err "  $me configure_container <name>   - configure devices in container"
+  err "  $me add_cplane_user              - add configured user for Onload Control Plane"
   err
   exit 1
 }
@@ -143,16 +144,39 @@ cmd_mknod() {
 }
 
 ######################################################################
+# The mod_params command is typically called in /etc/modprobe.d/onload.conf
 
 cmd_mod_params() {
   case "$1" in
     onload)
-      ONLOAD_CPLANE_USER=root
-      . /etc/sysconfig/openonload
+      if ! id -u "$ONLOAD_CPLANE_USER" >/dev/null 2>/dev/null; then
+        err "ERROR: Onload Control Plane user $ONLOAD_CPLANE_USER not found, defaulting to root."
+        ONLOAD_CPLANE_USER=root
+      fi
       echo cplane_server_uid=$(id -u $ONLOAD_CPLANE_USER) \
            cplane_server_gid=$(id -g $ONLOAD_CPLANE_USER)
       ;;
   esac
+  exit 0
+}
+
+######################################################################
+# The add_cplane_user command is recommended in /etc/sysconfig/openonload
+# and typically called by install processes to create 'onload_cplane' user.
+
+cmd_add_cplane_user() {
+  id -u "$ONLOAD_CPLANE_USER" >/dev/null 2>/dev/null && exit 0
+
+  # We do not require this home directory to exist
+  if command -v adduser; then
+    try adduser --system --no-create-home --home /run/openonload \
+                --shell /usr/sbin/nologin "$ONLOAD_CPLANE_USER" >/dev/null
+  elif command -v useradd; then
+    try useradd --system --home /run/openonload \
+                --shell /usr/sbin/nologin "$ONLOAD_CPLANE_USER" >/dev/null
+  else
+    fail "ERROR: Shadow utils not found. The user $ONLOAD_CPLANE_USER needs adding manually."
+  fi
   exit 0
 }
 
@@ -254,7 +278,7 @@ do_unload() {
   rc=0
   # onload_cp_server can take a while to die, let's do it first if no stacks present
   have_stacks || kill_cplane
-  # Old (pre-2011) systems had inverse dependency of sfc_affinity on 
+  # Old (pre-2011) systems had inverse dependency of sfc_affinity on
   # sfc_resource to modern ones. To allow old versions to unload try that first
   modusedby sfc_resource sfc_affinity && tryunload sfc_affinity
   tryunload af_onload      # Present in historical Onload versions
@@ -288,6 +312,7 @@ cmd_unload() {
 }
 
 ######################################################################
+# The post_install command is typically called in /etc/modprobe.d/onload.conf
 
 set_dev_perms() {
   get_dev_perms $1
@@ -327,6 +352,7 @@ cmd_reload() {
 
 while [ $# -gt 0 ]; do
   case "$1" in
+    -v)  set -x;;
     -*)  usage;;
     *)   break;;
   esac
@@ -335,6 +361,7 @@ done
 
 [ $# -ge 1 ] || usage
 
+ONLOAD_CPLANE_USER=root
 [ -f /etc/sysconfig/openonload ] && . /etc/sysconfig/openonload
 
 cmd="$1"
@@ -355,6 +382,9 @@ case "$cmd" in
     ;;
   configure_container)
     cmd_configure_container "$@"
+    ;;
+  add_cplane_user)
+    cmd_add_cplane_user
     ;;
   post_install)
     cmd_post_install "$@"
